### ISSUE TITLE
Resolve variables in RedrivePolicy

### ISSUE THREAD

**Issue by Nevon** [Nevon/serverless-sqs-local#1]
Given a set of resources like:

```
ProcessingQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-processing-${self:provider.stage}
    MessageRetentionPeriod: 1209600
    VisibilityTimeout: 60
    RedrivePolicy:
      deadLetterTargetArn:
        Fn::GetAtt:
        - ProcessingQueueDeadLetterQueue
        - Arn
      maxReceiveCount: 10
ProcessingQueueDeadLetterQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-processing-${self:provider.stage}-dead-letter-queue
    MessageRetentionPeriod: 1209600
```

Currently the plugin will omit the RedrivePolicy entirely when creating the queues in ElasticMQ, because it's not able to resolve the value of `Fn::GetAtt`.
