### ISSUE TITLE
Support executing lambdas locally in response to SQS event

### ISSUE THREAD

**Issue by harunsmrkovic** [Nevon/serverless-sqs-local#2]
👋 

I was not able to find a complete (or any) solution to this, so I suggest adding support for running lambdas in response to SQS event directly in this plugin.

For example, given a config like this:

```
resources:
  Resources:
    CryptoCreatedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: created-queue-local

functions:
  btcListen:
    handler: handler.btcListen
    events:
      - sqs: arn:aws:sqs:eu-central-1:${self:accountId}:created-queue-local
```

we'd make plugin listen to `created-queue-local`, and execute lambda `btcListen` with SQS Event when it arrives in a Queue, as AWS does it natively.

We can mimic AWS behaviour, as seen in this plugin: https://github.com/mj1618/serverless-offline-sns/blob/master/src/sns-adapter.ts#L104...

I can prepare PR if you'd like to add this.
